;
;  Emu80 v. 2.86
;  (c) Viktor Pykhonin <pyk@mail.ru>, 1997-2000
;
; This program is free software; you can redistribute it and/or modify
; it under the terms of the GNU General Public License as published by
; the Free Software Foundation; either version 2 of the License, or
; (at your option) any later version.
;
; This program is distributed in the hope that it will be useful,
; but WITHOUT ANY WARRANTY; without even the implied warranty of
; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
; GNU General Public License for more details.
;
; You should have received a copy of the GNU General Public License
; along with this program; if not, write to the Free Software
; Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
;

MODEL_R=0
MODEL_M=1
MODEL_P=2
MODEL_A=3
MODEL_S=4
MODEL_O=5
MODEL_M80=6
MODEL_U=7

MON_DEF=0

MON_O_1=1
MON_O_2=2
MON_O_PET=3

MON_R_32=1
MON_R_16=2
MON_R_4K=3
;MON_R_3=4

MON_S_1=1
MON_S_2=2
MON_S_M=3
MON_S_L=4

MON_M80_O=1
MON_M80_R=2

SPEED_NORM=2
SPEED_MEDIUM=1
SPEED_HIGH=0

MEM_NONE=0
MEM_W=1
MEM_RW=2

HOOKF809_YES=1
HOOKF809_NO=0

SCR_AUTO=2
SCR_LOW=0
SCR_HIGH=1
SCR_GRAPH=3

FONT_OEM=0
FONT_RK=1

REFR_RT=0
REFR_50=1
REFR_COMB=2

SND_ON=0
SND_OFF=1
SND_SB=2

TAPE_FILE=0
TAPE_SBOUT=1
TAPE_SBIN=2

SYSREQ_MENU=0
SYSREQ_RESET=1
SYSREQ_MODEL=2
SYSREQ_SAVESS=3
SYSREQ_LOADSS=4
SYSREQ_HELP=5
SYSREQ_QUIT=6
SYSREQ_MODELNOCLEAR=7
SYSREQ_DISKA=8
SYSREQ_DISKB=9
SYSREQ_ROM=10
SYSREQ_SPEEDUP=11
SYSREQ_SPEEDDOWN=12
SYSREQ_PAUSE=13
